services:
  - type: web
    name: anova-analysis-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    runtime: python-3.11
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health